### ISSUE TITLE
need to establish a license

### ISSUE THREAD

**Issue by triedel** [diydiagnostics/Photo-Float-Racks#1]
I'd like to make this repository public very soon but we need to decide on some kind of license.

**Comment by triedel** [comment]
I'm not to too familiar with open source licensing but I'm thinking something like "open attribution"

**Comment by Niam-Sword** [comment]
Read over the Open Data Commons Attribution License at https://opendatacommons.org/licenses/by/1-0/index.html, Sections 4.3 and 6.1a are pretty much exactly what I was envisioning - free non-commercial use with the condition that credit is given where it's due. Still need to look over other licenses but so far I think open attribution is appropriate for this.

**Comment by Andrew-kanutexas** [comment]
MIT License added 07/15/2021.
